config/routes.rb
Rails.application.routes.draw do

  resources :questions
  devise_for :users
  root 'home#index'

  # ActiveAdmin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  # API routes
  namespace :api do
    namespace :v1 do
      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        post :toggle_like, on: :member
        resources :comments, only: [:index, :create, :destroy]
      end
      resource :users, only: [:show, :update]
    end
  end

  # Other routes
  post "toggle_like", to: "likes#toggle_like", as: :toggle_like

  resources :comments, only: [:create, :destroy]
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, :tag, presence: true

  belongs_to :user

  has_many_attached :images

  validates :images, blob: { content_type: :image } 

  has_many :likes
  has_many :likers, through: :likes, source: :user

  has_many :comments

  def image_urls
    images.map do |image|
      Rails.application.routes.url_helpers.rails_blob_url(image, only_path: true)
    end
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < ApplicationController
  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token, only: [:toggle_like]

  def index
    @questions = Question.includes(:likes).all
    render json: @questions.to_json(include: :likes, methods: :image_urls), status: :ok
  end

  def show
    @question = Question.find(params[:id])
    render json: @question.as_json(include: :likes, methods: :image_urls), status: :ok
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      render json: @question, status: :created
    else
      render json: { errors: @question.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      render json: @question, status: :ok
    else
      render json: { errors: @question.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    render head: :no_content
  end

  def toggle_like
    @question = Question.find(params[:id])

    if @question.likes.exists?(user: current_user)
      @question.likes.where(user: current_user).destroy_all
    else
      @question.likes.create(user: current_user)
    end

    render json: { status: 'success' }, status: :ok
  end

  private

  def question_params
    params.require(:question).permit(:title, :tag, :user_id, images: [])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = Question.all
    flash.now[:notice] = "This is a flash message"
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to questions_path
    else
      render :new
    end

    # respond_to do |format|
    #   if @question.save
    #     format.html { redirect_to question_url(@question), notice: "Question was successfully created." }
    #     format.json { render :show, status: :created, location: @question }
    #   else
    #     format.html { redirect_to root_path, status: :unprocessable_entity, alert: @question.errors.full_messages }
    #     format.json { render json: @question.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to question_url(@question), notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:title, :tag, :user_id, images: [])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<div class="container" style="max-width: 500px; margin-top: 40px">
  <%= form_with(model: question, class: "question-form") do |form| %>
    <% if question.errors.any? %>
      <div class="alert alert-danger">
        <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>
        <ul>
          <% question.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_area :title, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :tag, class: "form-label" %>
      <%= form.text_field :tag, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :images, class: "form-label" %>
      <%= form.file_field :images, multiple: true, class: "form-control" %>
    </div>

    <div>
      <%= form.submit "Submit", class: "btn btn-warning text-white" %>
    </div>
  <% end %>

app/views/questions/_liker.html.erb
<div class="d-flex justify-content-between">
  <div class="d-flex">
    <%= image_tag liker.profile_picture.attached? ? liker.profile_picture : 'profile_pic.jpg', class: "img-thumbnail rounded-circle", style: "width: 2.5rem" %>
    <div class="d-flex flex-column mx-3 justify-content-center">
      <small class="fw-bold" style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;max-width:10rem"><%= link_to liker.username, class:  "a-decoration-none", style: "color: black", data: {turbo: 'false'} do %><%= liker.username %><% end %></small>
    </div>
  </div>

  <%= link_to root_path, class:"btn btn-warning", style: "text-decoration:none" do %>
    <small class="fw-bold text-white">Follow</small>
    <% end %>
</div>

app/views/questions/_question.html.erb
<div id="<%= dom_id question %>">


<div class="card" style="width: 70rem; margin: 1rem">
  <div class="card-header bg-white d-flex align-items-center"> 
    <% if question.user.profile_picture.attached? %>
      <%= image_tag question.user.profile_picture, class: "img-thumbnail rounded-circle", style: "width: 3%" %>
    <% else %>
      <%= image_tag "profile_pic.jpg", class: "img-thumbnail rounded-circle", style: "width: 3%" %>
    <% end %>
    <div style= "margin: 10px;">
    <%= question.user.username %>
    </div>
    
    <div class="ms-auto align-self-center"> 
      <div class="dropdown">
        <a class="text-dark fs-4" style="text-decoration:none" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          ...
        </a>

        <ul class="dropdown-menu">
          <li><%= button_to 'Delete post', question, method: :delete, class:"dropdown-item" %></li>
        </ul>
      </div>
    </div>
  </div>


  <div class="card-body">
    <img src="..." class="card-img-top" alt="">
    <h3 class="card-title"><%= question.title %></h3>
    <p class="card-text">
      <span class='badge bg-danger'><%= question.tag %></span>
    </p>
   
    <div class="card-text">
      <% question.images.each do |image| %>
        <%= image_tag image, class: 'img-thumbnail' %>
      <% end %>
    </div>
    <%= render "questions/question_actions", question: question %>

    <%= render "questions/question_comments", question: question %>
  
      <small class="text-muted"><%= time_ago_in_words(question.created_at) %></small>
   
  </div>

 

  
   <%= form_with url: comments_path, method: :post do |f| %>
    <div class="card-footer d-flex justify-content-between bg-white">
      <%= f.text_area :comment_body, class: "W-75", placeholder: "Add your comment...", style:"border:none" %>
      <%= f.hidden_field :question_id, value: question.id %>
      <%= f.submit "Comment", class: "btn btn-warning fw-bold", style: "background:none:border:none" %>
      </div>
    <% end %>
   
</div>
</div>

app/views/questions/_question_actions.html.erb
<%= turbo_frame_tag "question#{question.id}actions" do %>
    <div class="d-flex justify-content-start align-items-center gap-1 mt-2">
        <%= button_to toggle_like_path(question_id: question.id), method: :post, style: "border:none; background:none" do %>
            <i class="<%= question.likes.find_by(user: current_user) ? "bi bi-heart-fill" : "bi bi-heart" %>" 
      style="<%= question.likes.find_by(user: current_user) ? "color: #ffa903;" : "" %>"></i>
        <% end %>
    </div>
      <a href="#" data-bs-toggle="modal" data-bs-target="#question<%= question.id %>_likesModal" style="text-decoration:none" class="text-dark">
    <small class="fw-bold"><%= pluralize(question.likes.count, "like") %> </small><br>
    </a>

    <!-- Modal -->
  <div class="modal fade" id="question<%= question.id %>_likesModal" tabindex="-1" aria-labelledby="post<%= question.id %>_likesModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="question<%= question.id %>_likesModalLabel">Question Likes</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="d-flex flex-column gap-3" >
            <% question.likers.each do |liker| %>
              <%= render "questions/liker", liker: liker %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/questions/_question_comments.html.erb
<%= turbo_frame_tag "question#{question.id}comments" do %>
   <% if question.comments.count > 0 %>
   <small class="text-muted">View all <%= pluralize(question.comments.count, "comments") %> </small>
   <% end %>
   <% question.comments.last(5).each do |comment| %>
      <p class="card-text m-0"><span class="fw-bold"><%= comment.user.username %></span> <%= comment.body %></p>
   <% end %>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Show this question", @question %> |
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/index.html.erb
<!-- <p style="color: green"><%= notice %></p>

<h1>Questions</h1> -->

<%# <div id="questions"> %>
  <%# @questions.each do |question| %>
    <%# render question %>
    <%# <p> %>
      <%# link_to "Show this question", question %>
    <%# </p> %>
  <%# end %>
<%# </div> %>

<%# <%= link_to "New question", new_question_path %> 

app/views/questions/new.html.erb
<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/show.html.erb
<p style="color: green"><%= notice %></p>

  <%= render @question %>


<div>
  <%= link_to "Edit this question", edit_question_path(@question) %> |
  <%= link_to "Back to questions", questions_path %>

  <%= button_to "Destroy this question", @question, method: :delete %>
</div>