config/routes.rb
Rails.application.routes.draw do

  resources :questions
  devise_for :users
  root 'home#index'

  # ActiveAdmin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  # API routes
  namespace :api do
    namespace :v1 do
      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        post :toggle_like, on: :member
        resources :comments, only: [:index, :create, :destroy]
      end
      resource :users, only: [:show, :update]
    end
  end

  # Other routes
  post "toggle_like", to: "likes#toggle_like", as: :toggle_like

  resources :comments, only: [:create, :destroy]
end

app/views/layouts/_flash_messages.html.erb
<% if notice %>
    <p class="alert-success" ><%= notice %></p>
<% end %>

<% if alert %>
    <p class="alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white ">
  <div class="container-fluid w-75" >
    <%= link_to questions_path, class:"navbar-brand" do %>
       <%= image_tag 'logo.png' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="d-flex mx-auto" style="width: 70%;">
      <form class="d-flex w-100">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" style="border-color: #ffe1a6; border-width: 2px; width: 80%;">
        <button class="btn btn-outline-dark me-5" type="submit">Search</button>
      </form>
    </div>
    
    <div>
      <%= link_to new_question_path, class: 'btn btn-warning text-white font-weight-bold', style: 'font-size: 0.8rem; padding: 5px 10px; margin: 10px; white-space: nowrap;' do %>
        <button class='btn btn-warning text-white font-weight-bold' style='margin: 0; white-space: nowrap; border: none; background: none;'>
          <i class="bi bi-plus-circle" style="font-size: 1rem;"></i> Ask Question
        </button>
      <% end %>
    </div>
  
    <div class="dropdown d-flex">
      <a class="" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        <% if current_user && current_user.profile_picture.attached? %>
          <%= image_tag(current_user.profile_picture, class: "img-thumbnail rounded-circle me-5", style: "width: 4rem; height: 4rem; object-fit: cover" ) %>
        <% else %>
          <%= image_tag("profile_pic.jpg", class: "img-thumbnail rounded-circle me-5", style: "width: 4rem; height: 4rem; object-fit: cover") %>
        <% end %>
      </a>
      
      <ul class="dropdown-menu" >
        <li><%= link_to "Profile", root_path,  class: "dropdown-item" %></li>
        <li><%= button_to "Log out", destroy_user_session_path,  class: "dropdown-item", method: :delete %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geekquery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <% if current_user%>
    <%= render 'layouts/navbar'%>
  <% end %>  
    <div id="app"></div>
    <%= yield %>
  </body>
</html>